# Generated by Django 5.2.7 on 2025-10-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course/lesson/videos/'),
        ),
    ]
