# Generated by Django 5.2.7 on 2025-10-07 14:19

import course.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lesson_course_alter_lesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course/lesson/videos/', validators=[course.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
