# Generated by Django 5.2.6 on 2025-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_object',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='reviewer',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'content_type', 'object_id'), name='unique_review_per_object'),
        ),
    ]
